fix: revert browser targets
for some reason this causes an issue and the extension does not work.
error: Could not establish connection. Receiving end does not exist.